# Generated by Django 5.1.2 on 2024-10-16 11:26

import django.db.models.deletion
import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('newscategory', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='news_detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('newspos', models.BooleanField(blank=True, null=True)),
                ('othourname', models.CharField(blank=True, max_length=50, null=True)),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
                ('newsheador', models.CharField(blank=True, max_length=300, null=True)),
                ('newscontent', tinymce.models.HTMLField(blank=True, null=True)),
                ('newsimg', models.ImageField(blank=True, null=True, upload_to='img')),
                ('newscetegory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='newsapp.category')),
            ],
        ),
        migrations.CreateModel(
            name='comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('disc', models.TextField()),
                ('post_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='newsapp.news_detail')),
            ],
        ),
    ]
