# Generated by Django 5.1.2 on 2024-10-16 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news_detail',
            name='newsposition',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
