# Generated by Django 5.1.2 on 2024-10-17 04:29

import django.db.models.deletion
import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0002_news_detail_newsposition'),
    ]

    operations = [
        migrations.CreateModel(
            name='topstorynews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('newsposition', models.IntegerField(blank=True, null=True)),
                ('othourname', models.CharField(blank=True, max_length=50, null=True)),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
                ('newsheador', models.CharField(blank=True, max_length=300, null=True)),
                ('newscontent', tinymce.models.HTMLField(blank=True, null=True)),
                ('newsimg', models.ImageField(blank=True, null=True, upload_to='img')),
                ('newscetegory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='newsapp.category')),
            ],
        ),
    ]
