# Generated by Django 5.1.2 on 2024-10-17 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0003_topstorynews'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news_detail',
            name='newspos',
        ),
        migrations.DeleteModel(
            name='topstorynews',
        ),
    ]
